apiVersion: v1
kind: ConfigMap
metadata:
  name: crm-config
  namespace: default
  labels:
    app: nexus-crm
data:
  # Aurora writer endpoint from your RDS cluster[cite: 2, 5]
  DB_WRITER_HOST: "main-aurora-cluster.cluster-cehh4jojvvsh.us-east-1.rds.amazonaws.com"
  # Aurora reader endpoint from your RDS cluster[cite: 2, 5]
  DB_READER_HOST: "main-aurora-cluster.cluster-ro-cehh4jojvvsh.us-east-1.rds.amazonaws.com"
  DB_PORT:        "3306"
  # Matches the default in your variables.tf[cite: 4, 5]
  DB_NAME:        "myappdb" 
  PORT:           "3001"
  CORS_ORIGIN:    "*"