apiVersion: v1
kind: Secret
metadata:
  name: crm-db-secret
  namespace: default
  labels:
    app: nexus-crm
type: Opaque
# Values must be base64-encoded:  echo -n "yourvalue" | base64
stringData:
  DB_USER:     "admin"
  DB_PASSWORD: "123456789"
