name: Build and Push NexusCRM

on:
  push:
    branches: [ "main" ] # Triggers the build when you push to the main branch

env:
  # Opt into Node.js 24 to resolve deprecation warnings for actions
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          # Use the Personal Access Token stored in your GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Tags the image for your specific Docker Hub namespace
          tags: mohamedelsayed215/nexus-crm:latest
          # Leveraging GitHub Actions cache to speed up subsequent builds
          cache-from: type=gha
          cache-to: type=gha,mode=max
